name: Deploy PlainAuth Webs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEBUG: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read Peoject version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check Docker username
        run: |
          echo ${{ secrets.DOCKER_USERNAME }}
          echo ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Docker Hub #登陆docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} #docker的用户名
          password: ${{ secrets.DOCKER_PASSWORD }} #docker的密码

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: aaamrh/plainauth-web

      - name: ssh docker login
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.YUANMENG_HOST }}
          username: ${{ secrets.YUANMENG_USER }}
          password: ${{ secrets.YUANMENG_PASSWORD }}
          script: cd ~/scripts && sh plainauth-web-deploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }} #运行脚本

      - name: Send Feishu Message
        if: always()
        env:
          DEPLOY_STATUS: ${{ job.status }}
        run: |
          if [ "$DEPLOY_STATUS" = "success" ]; then
            status="✅ 成功"
            message="部署 URL: ${{ steps.deployment.outputs.page_url }}"
          else
            status="❌ 失败"
            message="请检查 Actions 日志以获取更多信息: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          fi

          curl -X POST -H "Content-Type: application/json" \
            -d '{
              "msg_type": "text",
              "content": {
                "text": "monitor page 部署 '"$status"'！\n项目: ${{ github.repository }}\n分支: ${{ github.ref }}\n提交信息: ${{ github.event.head_commit.message }}\n'"$message"'"
              }
            }' \
            ${{ secrets.FEISHU_DEPLOY_ROBOT_URL }}
